kafka_image: wurstmeister/kafka:2.13-2.6.0
kafka_broker_id: 1
kafka_container_name: "kafka-{{ kafka_broker_id | string }}"
kafka_advertised_host_name: ip_address
kafka_advertised_port: 9092
kafka_zookeeper_connect: "zoo1_ip:2181,zoo2_ip:2181,zoo3_ip:2181"
kafka_create_topics: "test:10:2,test2:10:2"
kafka_heap_opts: "-Xmx1g -Xms512m -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
kafka_num_replica_fetchers: 4
kafka_log_retention_hours: 2
kafka_zookeeper_connection_timeout_ms: 6000
kafka_num_network_threads: 8
kafka_socket_receive_buffer_bytes: 1048576
kafka_socket_send_buffer_bytes: 1048576
kafka_queued_max_requests: 16
kafka_fetch_purgatory_purge_interval_requests: 100
kafka_producer_purgatory_purge_interval_requests: 100
