---
- name: Create datasources directory
  file:
    path: "/etc/{{ grafana_container_name }}/provisioning/datasources"
    state: directory
    mode: "0755"
  tags:
    - grafana

- name: Create dashboards directory
  file:
    path: "/etc/{{ grafana_container_name }}/provisioning/dashboards"
    state: directory
    mode: "0755"
  tags:
    - grafana

- name: Copy kafka dashboard
  copy:
    src: "{{ role_path }}/files/dashboard_kafka.json"
    dest: "/etc/{{ grafana_container_name }}/provisioning/dashboards/kafka.json"
    mode: "0644"
  notify:
    - Restart grafana
  tags:
    - grafana

- name: Create prometheus datasource provision
  template:
    src: "{{ role_path }}/templates/datasource-prometheus.yml.j2"
    dest: "/etc/{{ grafana_container_name }}/provisioning/datasources/prometheus.yml"
    mode: "0644"
  notify:
    - Restart grafana
  tags:
    - grafana

- name: Grafana volume
  docker_volume:
    name: "{{ grafana_container_name }}"
  tags:
    - grafana

- name: Grafana container
  community.general.docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}"
    restart_policy: always
    container_default_behavior: compatibility
    network_mode: host
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user | string }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password | string }}"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/kafka.json"
    volumes:
      - "{{ grafana_container_name }}:/var/lib/grafana"
      - "/etc/{{ grafana_container_name }}/provisioning/:/etc/grafana/provisioning/"
  tags:
    - grafana
