- name: Kafka-exporter container
  community.general.docker_container:
    name: kafka-exporter
    image: "{{ kafka_exporter_image }}"
    restart_policy: always
    container_default_behavior: compatibility
    command: "{{ kafka_exporter_arguments }}"
    network_mode: host
  tags:
    - kafka-exporter
