---
- name: zookeeper container
  community.general.docker_container:
    name: "zookeeper-{{ zookeeper_id | string }}"
    image: "{{ zookeeper_image | string }}"
    env:
      ZOO_MY_ID: "{{ zookeeper_id | string }}"
      ZOO_SERVERS: "{{ zookeeper_servers_list | string }}"
    network_mode: host
    state: started
  tags:
    - zookeeper
